### ISSUE TITLE
load.sql issue

### ISSUE THREAD

**Issue by MarkivK89** [paulhoekman/mfa-tools#1]
I've been trying to load the load.sql script into my database and come across an error: 

Table 'mfa-tools.mfa_sources_flags' does not exist.

So the script tries to alter a table that does not exist. Any advice? Am I doing something wrong? Thanks!

**Comment by paulhoekman** [comment]
Thanks for the comment! It likely isn't you - I likely forgot dumping the structure of that table into the load.sql file. What I've done in the most recent commit is dump the full database structure, so you can just import this file into your database and you should be fine. 

If anything else arises feel free to open a new issue.
